-- PRISMA Editorial articles table
-- Receives content from prisma-content-engine via API

CREATE TABLE IF NOT EXISTS editorial_articles (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug          TEXT UNIQUE NOT NULL,
  title         TEXT NOT NULL,
  subtitle      TEXT,
  body_html     TEXT NOT NULL,
  body_text     TEXT,                    -- plain text for SEO/search
  excerpt       TEXT NOT NULL,           -- 160 chars max, for meta description
  category      TEXT NOT NULL DEFAULT 'editorial',
                                         -- editorial | laboratory | fastfood
  film_slug     TEXT,                    -- links to /films/{slug}
  film_title    TEXT,
  film_year     INTEGER,
  director      TEXT,
  color_slug    TEXT,                    -- PRISMA iconic color slug
  cover_image   TEXT,                    -- URL of cover image
  og_image      TEXT,                    -- OG image URL (generated by image-engine)
  tags          TEXT[] DEFAULT '{}',
  reading_time  INTEGER,                 -- minutes
  word_count    INTEGER,
  published_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  published     BOOLEAN NOT NULL DEFAULT false,
  featured      BOOLEAN NOT NULL DEFAULT false,
  author        TEXT NOT NULL DEFAULT 'PRISMA Editorial',
  -- SEO fields
  meta_title    TEXT,
  meta_desc     TEXT,
  focus_keyword TEXT,
  schema_type   TEXT DEFAULT 'Article',  -- Article | Review | NewsArticle
  -- Content engine fields
  source_url    TEXT,
  gemini_score  INTEGER,
  voice         TEXT DEFAULT 'editorial' -- editorial | radar | focus
);

CREATE INDEX IF NOT EXISTS idx_editorial_published
  ON editorial_articles(published_at DESC)
  WHERE published = true;

CREATE INDEX IF NOT EXISTS idx_editorial_category
  ON editorial_articles(category)
  WHERE published = true;

CREATE INDEX IF NOT EXISTS idx_editorial_film_slug
  ON editorial_articles(film_slug)
  WHERE film_slug IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_editorial_featured
  ON editorial_articles(featured, published_at DESC)
  WHERE published = true AND featured = true;

-- Enable RLS
ALTER TABLE editorial_articles ENABLE ROW LEVEL SECURITY;

-- Public read access for published articles
CREATE POLICY "Public read published articles"
  ON editorial_articles FOR SELECT
  USING (published = true);

-- Service role can do everything (for content engine API)
CREATE POLICY "Service role full access"
  ON editorial_articles FOR ALL
  USING (auth.role() = 'service_role');
